require('settings').setup()
require('maps')

require('plugins')
require('plugins.autopairs')
require('plugins.presence')
require('plugins.colorizer')
require('plugins.comment')
require('plugins.nvim-tree')
require('plugins.mason')
require('plugins.lspconfig')
require('plugins.nvim-cmp')
require('plugins.treesitter')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.gitsigns')
